Mark nix::unistd::fork as unsafe.
nix-rust/nix pull request #1293
Opened 2020-09-10 20:06 UTC by vi

Fix tests. No change in documentation.

Resolves #1030.

Don't forget to bump major version number to `0.19`.

2020-09-10 20:07 UTC, vi commented
r? @asomers

2020-09-11 22:56 UTC, asomers requested changes
Since this change is backwards-incompatible, it needs a good explanation in the CHANGELOG.  Could you please add one?

2020-09-11 23:10 UTC, vi commented
Added changelog entry.

2020-09-12 02:05 UTC, asomers commented
Now the compiler is complaining about "unnecessary unsafe block".  Can you please fix those?

2020-09-12 11:02 UTC, vi commented
It not caused by the changed code, it's just master brach is not buildable anymore.

I submitted a separate pull request with an easy way to fix it: #1294.

2020-09-13 16:03 UTC, asomers approved these changes
This LGTM, though it will obviously need to be rebased after #1294 lands.

2020-09-20 14:14 UTC, vi commented
@asomers Rebased the pull request.

2020-10-03 10:10 UTC, vi commented
@asomers, Shall something more to be done about this pull request?

2020-10-03 13:35 UTC, asomers approved these changes
Nope.  I think it's good to go.

bors r+

2020-10-03 14:17 UTC, merged