Dir: Implement `IntoIterator` for `Dir`
nix-rust/nix pull request #1333
Opened 2020-11-15 21:48 UTC by wmanley

This is useful to allow returning an iterator based on a directory iterator
without needing a self-referential struct.

2020-11-28 22:36 UTC, asomers commented
I don't understand the motivation for this PR.  Can you please show an example?  What does this enable that couldn't as easily be done with the existing API?

2020-11-29 16:29 UTC, wmanley commented
Here's where I use it: https://github.com/wmanley/ostree-oxide/blob/d3f38da61deb614be67d3705519df0235e4d2e84/ostree-repo/src/lib.rs#L253-L281

This allows me to return an `Iterator` that owns the `Dir`. This is important because I open the `Dir` in the function that returns the `Iterator`.  I couldn't work out how to do this with the existing API short of self-referential structs.

2020-11-29 16:48 UTC, asomers commented
Would it be possible to add a usage example?

2020-11-29 23:26 UTC, wmanley commented
> Would it be possible to add a usage example?

Done

2021-02-11 17:27 UTC, wmanley commented
Ping: Are there any other changes you'd like to make this suitable to go in?

2021-02-13 03:18 UTC, asomers requested changes
I think this looks good.  It just needs three small things:
1) CHANGELOG entry (may require a rebase to avoid conflicts)
2) Squash
3) Doc comment for `OwningIter`.  It can simply say "The return type of [`Dir::into_iter`]".

2021-02-15 15:18 UTC, wmanley commented
> I think this looks good. It just needs three small things:

Thanks for the review. I've done these three things.

CI on "OSX x86_64" failed with:

> warning Agent process on a persistent worker exited unexpectedly!

but I can't imagine that the failure was caused by this PR.

2021-02-15 15:37 UTC, asomers approved these changes
The OSX failure looks like perhaps GCE yanked the VM out from under us.  That happens sometimes.

bors r+

2021-02-15 15:52 UTC, merged