Add `PTRACE_EVENT_STOP` enum variant
nix-rust/nix pull request #1335
Opened 2020-11-16 07:24 UTC by GabrielMajeri

Adds the `PTRACE_EVENT_STOP` variant to the `ptrace::Event` enum.

Smaller part of #1279

2020-11-18 02:44 UTC, ranweiler commented
Closes #1334.

2021-08-14 15:39 UTC, asomers requested changes
Needs a CHANGELOG entry, please.

2021-08-15 13:40 UTC, GabrielMajeri commented
@asomers done

2021-08-18 02:04 UTC, asomers commented
You need to rebase to fix the test failures.

2021-08-21 20:05 UTC, asomers approved these changes
bors r+

2021-08-21 20:29 UTC, merged