Add support for `SockAddr::Link` when receiving packets
nix-rust/nix pull request #1344
Opened 2020-11-27 20:58 UTC by internetionals

fixes #1343

2020-11-27 23:00 UTC, asomers requested changes
Looks pretty good.  Let's just try adding fuchsia support.

2020-11-28 21:54 UTC, asomers commented on src/sys/socket/mod.rs
>          #[cfg(any(target_os = "android", target_os = "linux"))]
Err, wait on that.  Fuchsia support hasn't merged yet.

2020-12-01 07:43 UTC, internetionals commented on CHANGELOG.md
> +- Fixed calling `recvfrom` on an `AddrFamily::Packet` socket (#[1344](https://github.com/nix-rust/nix/pull/1344))
Done

2020-12-01 07:46 UTC, internetionals commented on src/sys/socket/mod.rs
>          #[cfg(any(target_os = "android", target_os = "linux"))]
While the  Fuchsia's libc (being a based on a Musl fork) has the defines and structures, I don't think it actually supports raw packet sockets (based on a cursory glance of it's own API) and that they're really just relics of the fork. But given that it's in their libc might be enough of a reason to support it.

2020-12-02 04:18 UTC, asomers commented
I'm afraid you'll need to rebase to fix the CHANGELOG.

2021-01-11 16:06 UTC, internetionals commented
@asomers is there anything left I can do to get this over the finish line?

2021-01-31 21:42 UTC, asomers approved these changes
Sorry I've been ignoring this.  I don't have much time to work on Nix anymore.  But the PR looks good now.

bors r+

2021-01-31 22:08 UTC, merged