add IP_MULTICAST_IF for sockopt
nix-rust/nix pull request #1363
Opened 2020-12-15 07:10 UTC by keepsimple1

IP_MULTICAST_IF is not supported by `sockopt` in `nix`. See issue #1360 .

According to Linux [man page](https://man7.org/linux/man-pages/man7/ip.7.html), IP_MULTICAST_IF is used in this way: 

quote:
```
IP_MULTICAST_IF (since Linux 1.2)
              Set the local device for a multicast socket.  The argument for
              setsockopt(2) is an ip_mreqn or (since Linux 3.5) ip_mreq
              structure similar to IP_ADD_MEMBERSHIP, or an in_addr struc‐
              ture.  (The kernel determines which structure is being passed
              based on the size passed in optlen.)  For getsockopt(2), the
              argument is an in_addr structure.
```

Please review this patch.  Also I have a question:  how do we add automated testing for such `sockopt` in `nix`? I've added a test case in my own code that uses `nix` and it works, but don't know about the practice of testing inside `nix`. Thanks.

2020-12-16 23:03 UTC, asomers commented
Nix doesn't currently use anything fancy like mocking for tests.  Just try to exercise the socket option.  Don't write an exhaustive test suite for it; that's a job for the kernel maintainers.  Nix's test suite should do just enough to ensure that the bindings are correct.

2020-12-24 21:19 UTC, keepsimple1 commented
Thanks @asomers for your answers. I've updated the diff and the PR Description, adding a test case. Please take a look when you have time.

2021-01-31 22:15 UTC, asomers requested changes
My man page says `The use of IP_MULTICAST_IF is not recommended, as multicast memberships are scoped to each individual interface.  It is supported for legacy use only...`.  Given that, we probably should't add Nix support for it.  Is there something you need it for that can't be done any other way?

2021-01-31 22:15 UTC, asomers commented on src/sys/socket/sockopt.rs
> +cfg_if! {
`cfg_if` is helpful when you expect to have `else` or `else if` blocks.  But in cases like this, it's simpler to do:
```rust
#[cfg(...)]
sockopt_impl!(...)
```

2021-01-31 22:15 UTC, asomers commented on src/sys/socket/mod.rs
> +        #[repr(transparent)]
Does the option work with IPv6?  If so you should use an enum type.  Or maybe define different Nix sockopts, one for each supported address type.

2021-02-02 06:19 UTC, keepsimple1 commented
> My man page says `The use of IP_MULTICAST_IF is not recommended, as multicast memberships are scoped to each individual interface. It is supported for legacy use only...`. Given that, we probably should't add Nix support for it. Is there something you need it for that can't be done any other way?

Could you please share where I can find this man page you referred to? Thanks.

2021-02-07 02:35 UTC, asomers commented
https://www.freebsd.org/cgi/man.cgi?query=ip&apropos=0&sektion=4&manpath=FreeBSD+12.2-RELEASE+and+Ports&arch=default&format=html

2021-02-07 06:54 UTC, keepsimple1 commented
> https://www.freebsd.org/cgi/man.cgi?query=ip&apropos=0&sektion=4&manpath=FreeBSD+12.2-RELEASE+and+Ports&arch=default&format=html

Thanks.  Looks like FreeBSD deems it legacy (while Linux seems not).

And I found a workaround in my project at this point. I will close this PR for now until someone found its use again.

2021-02-07 06:54 UTC, closed without merging