Add new symbol for linux IP_MULTICAST_ALL
nix-rust/nix pull request #1418
Opened 2021-04-06 00:05 UTC by anth1y

this closes #1199 
/cc @asomers

2021-04-06 00:10 UTC, asomers requested changes
You also need a CHANGELOG entry.  And if possible, a test.  I don't know what this option does.  Is it practical to add a test for it in Nix?

2021-04-06 00:10 UTC, asomers commented on src/sys/socket/sockopt.rs
> +cfg_if! {
You shouldn't use `cfg_if` if you're only going to have one clause.  Instead, just do
```rust
#[cfg(target_os = "linux")]
whatever
```

2021-04-06 00:10 UTC, asomers commented on src/sys/socket/sockopt.rs
> +	 if #[cfg(any(target_os = "linux"))] {
The symbol is defined on Android, too.

2021-04-06 01:26 UTC, anth1y commented
I dont think this needs a test but i'll defer to your judgement here:

```
       IP_MULTICAST_ALL (since Linux 2.6.31)
              This option can be used to modify the delivery policy of
              multicast messages to sockets bound to the wildcard
              INADDR_ANY address.  The argument is a boolean integer
              (defaults to 1).  If set to 1, the socket will receive
              messages from all the groups that have been joined
              globally on the whole system.  Otherwise, it will deliver
              messages only from the groups that have been explicitly
              joined (for example via the IP_ADD_MEMBERSHIP option) on
              this particular socket.
```

2021-04-07 03:29 UTC, asomers requested changes

2021-04-07 03:29 UTC, asomers commented on CHANGELOG.md
> +  (#[1411](https://github.com/nix-rust/nix/pull/1411))
Looks like you copy/pasted the wrong PR number.

2021-04-07 03:29 UTC, asomers commented on src/sys/socket/sockopt.rs
> +cfg_if! {
Did you forget to push this change?

2021-04-10 01:59 UTC, asomers reviewed
Better.  Can you please squash your commits?  Then we'll be good to go.

2021-04-11 21:55 UTC, anth1y commented
going to close this my branch is super polluted ...

2021-04-11 21:55 UTC, closed without merging