Add new linux symbol for multicast-all
nix-rust/nix pull request #1423
Opened 2021-04-11 23:37 UTC by anth1y

this closes #1199 

/cc @asomers

2021-04-17 14:29 UTC, asomers requested changes

2021-04-17 14:29 UTC, asomers commented on src/sys/socket/sockopt.rs
> +[cfg(any(target_os = "linux", target_os = "android"))]
Syntax error: you're missing the `#`

2021-04-17 14:38 UTC, anth1y commented on src/sys/socket/sockopt.rs
> +[cfg(any(target_os = "linux", target_os = "android"))]
fixed

2021-04-18 14:40 UTC, anth1y commented
ugh it looks like my rust auto formatter struck again... :(

2024-03-19 03:30 UTC, closed without merging