constify from_raw and as_raw for Uid, Gid and Pid and Uid::is_root
nix-rust/nix pull request #1429
Opened 2021-04-21 09:53 UTC by Blub

Make some integer wrapper methods `const fn`.

* `Uid::from_raw`
* `Uid::as_raw`
* `Uid::is_root`
* `Gid::from_raw`
* `Gid::as_raw`
* `Pid::from_raw`
* `Pid::as_raw`

(Changelog mentions rust 1.40.0 as minimum required version which seems to compile this fine (using 1.40.0 from rustup))

2021-04-22 14:07 UTC, Blub commented
I don't think the failed check is due to this patch...

2021-04-23 15:35 UTC, asomers requested changes
Thanks for the patch.  Other than a PR link to the CHANGELOG, it looks good.

2021-04-23 15:35 UTC, asomers commented on CHANGELOG.md
> +- Made `Uid::is_root` a `const fn`
Needs a PR link.

2021-04-26 07:07 UTC, Blub commented on CHANGELOG.md
> +- Made `Uid::is_root` a `const fn`
updated with the links

2021-05-01 20:21 UTC, asomers approved these changes
bors r+

2021-05-01 20:46 UTC, merged