Add getresuid() and getresgid() to unistd
nix-rust/nix pull request #1430
Opened 2021-04-23 14:50 UTC by jerylvaz

2021-04-23 15:00 UTC, asomers requested changes

2021-04-23 15:00 UTC, asomers commented on test/test_unistd.rs
> +#[cfg(target_os = "linux")]
libc also implements these functions on Android.  But they're actually implemented on some of the BSDs, too.  Best would be to make a PR to libc that adds bindings everywhere they're implemented, then broaden your `cfg` restriction in Nix appropriately.

2021-04-23 15:00 UTC, asomers commented on test/test_unistd.rs
> +    // Assume that tests are never run as root
LOL!  Of course the tests sometimes run as root!  Some tests only work when run as root!

2021-04-26 08:22 UTC, jerylvaz commented
@asomers  What should be done with the unrelated test failure?

2021-05-01 20:42 UTC, asomers requested changes

2021-05-01 20:42 UTC, asomers commented on src/unistd.rs
> +#[cfg(any(target_os = "android", target_os = "linux", target_os = "openbsd"))]
This will fail to compile for OpenBSD.  You need to open a PR with https://github.com/rust-lang/libc first.

2021-05-16 02:30 UTC, asomers commented on src/unistd.rs
> +    pub fn getresuid() -> Result<(Uid, Uid, Uid)> {
Returning a tuple is a very old fashioned and failure-prone technique.  Better to return a structure.  That way the meaning is obvious even without consulting the documentation.  Something like:
```rust
struct ResUid {
    real: Uid,
    effective: Uid,
    saved: uid
}
```

2021-05-30 14:38 UTC, asomers commented
Looks good, but you'll have to rebase to fix the CI failure on FreeBSD.

2021-05-31 14:04 UTC, asomers requested changes

2021-05-31 14:04 UTC, asomers commented on CHANGELOG.md
> +### Added
Please fix the CHANGELOG.  There was a merge error, and now there are two "Added" sections.

2021-05-31 14:32 UTC, asomers approved these changes
bors r+

2021-05-31 15:04 UTC, merged