Expose SockAddr::from_raw_sockaddr
nix-rust/nix pull request #1447
Opened 2021-06-08 04:08 UTC by coolreader18

I also noticed the `SockAddr/InetAddr::to_str` functions were entirely redundant - `ToString` exists for that, & has a blanket impl on `T: Display`.

2021-06-12 18:20 UTC, asomers requested changes
Could you please split these two changes up, since they're unrelated?  Also, it would be good to deprecate `to_str` for a few releases before removing it entirely.

2021-08-21 19:54 UTC, coolreader18 commented
@asomers Could you take a look at this again? I split out the other change into #1495 as well.

2021-08-21 20:04 UTC, asomers approved these changes
bors r+

2021-08-21 22:00 UTC, coolreader18 commented
Huh. I think the failure was just cause of the conflict in CHANGELOG?

2021-08-22 00:35 UTC, asomers commented
bors retry

2021-08-22 00:51 UTC, merged

2021-08-22 22:32 UTC, coolreader18 commented
Ah, shoot, just realized the functionality I was looking for was in `sockaddr_storage_to_addr` - however, I'm pretty sure that should also be unsafe and take a `*const sockaddr` instead of an `&sockaddr_storage`, since it seems like there are some `assume_init` calls that might not be valid as the full extent of the sockaddr_storage might not actually get initialized if the address is only a couple bytes in size.