unistd: Add conversion from User to libc::passwd
nix-rust/nix pull request #1471
Opened 2021-07-18 09:44 UTC by orvij

Add `From<User> for libc::passwd` trait implementation to convert a `User` into a `libc::passwd`

Implementation consumes the `User` struct, giving ownership over the internal members to the `libc::passwd` struct

2021-07-24 19:52 UTC, asomers requested changes
Just add a CHANGELOG entry, and don't forget to mention the change to the gecos field.

2021-07-24 19:52 UTC, asomers commented on src/unistd.rs
> +    #[cfg(not(all(target_os = "android", target_pointer_width = "32")))]
This looks like an extra change that was not mentioned in the commit message.  Could you please mention it?

2021-07-24 23:46 UTC, asomers requested changes
Some kind of weird merge error screwed up the changelog.  There are three "Added" sections now.

2021-07-25 00:09 UTC, orvij commented
> Some kind of weird merge error screwed up the changelog. There are three "Added" sections now.

Sorry about that, when I rebased some things went weird. Fixed

2021-07-25 00:17 UTC, asomers approved these changes
bors r+

2021-07-25 00:28 UTC, merged