sys/stat: add a safe wrapper for mknodat(2)
nix-rust/nix pull request #1473
Opened 2021-07-22 08:24 UTC by lucab

This introduces a new `mknodat` helper.

Ref: https://pubs.opengroup.org/onlinepubs/9699919799/functions/mknod.html

2021-07-22 12:24 UTC, otavio approved these changes

2021-07-24 19:56 UTC, asomers requested changes
Looks good.  How about a test?

2021-07-28 12:50 UTC, lucab commented
I was hoping to copy+adjust the `mknod` test, but there was none; I thus added a basic test for both.
I initially started writing a chardev test, but then realized it could be problematic on `nodev` mountpoints so I went for a simpler regular-file one instead (which is not supported on freebsd though).
Also rebased on current master to solve changelog conflict. CI is green. This is ready for another review pass now.

2021-07-29 01:22 UTC, asomers approved these changes
LGTM.

bors r+

2021-07-29 01:53 UTC, merged