Relax assertions in sockaddr_storage_to_addr to match the documentation.
nix-rust/nix pull request #1486
Opened 2021-08-10 05:56 UTC by khuey

Fixes #1479

2021-08-10 23:52 UTC, asomers requested changes
The tests you modified are now doing two completely different things.  Better to split them up, testing only the minimal amount of functionality in each test.

2021-08-14 15:25 UTC, asomers requested changes

2021-08-14 15:25 UTC, asomers commented on test/sys/test_socket.rs
> +        // assert_eq!(mem::size_of::<sockaddr>(), ffi_size as usize);
You should delete this comment

2021-08-15 00:33 UTC, khuey commented on test/sys/test_socket.rs
> +        // assert_eq!(mem::size_of::<sockaddr>(), ffi_size as usize);
Done.

2021-08-18 02:01 UTC, asomers commented
You'll need to rebase to fix the test failures.

2021-08-18 02:21 UTC, khuey commented
Done.

2021-08-18 02:25 UTC, asomers commented
Just one more thing: would you mind squashing your commits?

2021-08-18 02:52 UTC, khuey commented
Done.

2021-08-18 04:12 UTC, asomers approved these changes
bors r+

2021-08-18 14:38 UTC, asomers commented
bors retry

2021-08-18 15:18 UTC, merged

2021-08-18 15:47 UTC, khuey commented
Thanks.