Lower hard limit in setrlimit example
nix-rust/nix pull request #1536
Opened 2021-09-19 18:03 UTC by rtzoeller

The current value causes the doc test to fail on Fedora 34 for unprivileged users. The value can be lowered without meaningfully changing the example.

Previously the example failed with EPERM.

2021-09-19 18:06 UTC, rtzoeller commented
Obtained the new value by building and running the following C program as a non-root user:

```c
#include <stdio.h>
#include <sys/resource.h>

int main() {
    struct rlimit rlimit;
    int retval = getrlimit(RLIMIT_NOFILE, &rlimit);
    printf("%d\n", rlimit.rlim_cur);
    printf("%d\n", rlimit.rlim_max);
}
```

Results in

```
1024
524288
```

2021-09-19 18:14 UTC, rtzoeller commented
Alternatively, this code block could be marked as `no_run`.

2021-09-19 18:48 UTC, asomers requested changes
I think you should make the limit way smaller, like maybe 512/1024 or something.  There's no reason it should be this high.

2021-09-23 02:18 UTC, asomers approved these changes

2021-09-28 03:36 UTC, asomers commented
I guess I forgot to order bors around earlier.

bors r+

2021-09-28 03:44 UTC, merged