Add `MsgFlag::MSG_NOSIGNAL`
nix-rust/nix pull request #1670
Opened 2022-03-06 08:26 UTC by i509VCB

(I guess I will see if I did the cfg block correctly)

2022-03-06 15:06 UTC, asomers commented
Looks good, but could you please add a CHANGELOG entry?

2022-03-06 21:39 UTC, i509VCB commented
Changelog is done, I checked libc and realized I forgot illumos so that is added.

2022-03-06 22:20 UTC, asomers requested changes

2022-03-06 22:20 UTC, asomers commented on CHANGELOG.md
> +- Added `MSG_NOSIGNAL` for Android, Dragonfly, FreeBSD, Fuchsia, Haiku, Illumos, Linux, NetBSD, OpenBSD and Solaris.
Please follow the format of the other changelog entries.

2022-03-08 23:46 UTC, rtzoeller commented
bors r+

2022-03-09 00:02 UTC, merged