Make `uname` always safe
nix-rust/nix pull request #1672
Opened 2022-03-10 09:55 UTC by koute

Currently `uname` doesn't check for errors and just blindly assumes that it always succeeds. According to the manpage this function can fail, even though no actual errors are defined:

```
RETURN VALUE
       Upon successful completion, a non-negative value shall be returned.  Otherwise, -1 shall be returned and errno set to indicate the error.

ERRORS
       No errors are defined.

       The following sections are informative.
```

Looking at [the glibc's sources](https://github.com/bminor/glibc/blob/b92a49359f33a461db080a33940d73f47c756126/posix/uname.c#L29) we can see that it indeed could fail if the internal `gethostname` call fails for some reason.

This code also assumes that every field of `utsname` is going to be initialized by the call to `uname`, which apparently is also not true. Even though the interface doesn't expose this field so it's not a problem in practice (although it might be UB since we do call `assume_init` on the whole struct) [the `utsname` does have a `domainname` field](https://docs.rs/libc/0.2.119/libc/struct.utsname.html) which glibc doesn't initialize.

The code also assumes that every field is a valid UTF-8 string, which is also technically not guaranteed.

The code also assumes that every field will be null terminated, which might not be true if any of the strings are too long (since glibc uses `strncpy` which will *not* null-terminate the string if it ends up running out of space).

This PR should fix all of these problems.

This is a breaking change.

2022-03-13 22:28 UTC, asomers requested changes
Do you know of any cases where the strings _aren't_ valid UTF-8 ?  It is certainly more convenient for the user if we return a `&str` than a `&[u8]`.  Perhaps do a checked conversion to utf8?

2022-03-13 22:28 UTC, asomers commented on src/sys/utsname.rs
> +pub fn uname() -> Result<UtsName, Errno> {
```suggestion
pub fn uname() -> Result<UtsName> {
```

2022-03-13 22:28 UTC, asomers commented on src/sys/utsname.rs
> +use crate::Errno;
```suggestion
use crate::Result;
```

2022-03-16 05:16 UTC, koute commented
> Do you know of any cases where the strings _aren't_ valid UTF-8 ?

Not specifically, but e.g. someone could set a non-UTF8 hostname with `sethostname` which will end up in the `nodename` returned here.

> It is certainly more convenient for the user if we return a `&str` than a `&[u8]`. Perhaps do a checked conversion to utf8?

Well, I see three possibilities here:

1. Return a `&[u8]`.
2. Return a `&str` and panic if it can't be converted.
3. Return a `Result<&str, Utf8Error>`.

Converting the `&[u8]` to string on the user's side is just a matter of changing `utsname.nodename()` to `std::str::from_utf8(utsname.nodename())?` so it's not *that* big of a deal, and it's not like this is a super frequently used function. I'd rather not go for (2) because I think libraries shouldn't panic on errors, and (3) feels like a halfway measure.

2022-03-19 18:27 UTC, asomers commented
What if it returns an `OsString`?  Those are allowed to be non-UTF8.  See fcntl::readlink for an example.  Would that work?

2022-03-20 04:39 UTC, koute commented
> What if it returns an `OsString`? Those are allowed to be non-UTF8. See fcntl::readlink for an example. Would that work?

`OsString` allocates so that's not great, but I guess `&OsStr` should indeed work. Done!

2022-03-20 17:38 UTC, rtzoeller commented
LGTM; can you squash and rebase?

2022-03-23 05:30 UTC, koute commented
> LGTM; can you squash and rebase?

Done!

2022-03-24 02:56 UTC, asomers approved these changes
bors r+

2022-03-24 03:38 UTC, merged