add GETFPREGS and SETFPREGS ptrace calls
nix-rust/nix pull request #1844
Opened 2022-10-11 14:21 UTC by bmc-msft

Added two new functions to the ptrace module: getfpregs and setfpregs gets and sets the floating point registers of the tracee.

This is based on #1426, but updated to the latest master.

2022-10-11 14:25 UTC, bmc-msft commented
CC: @nemarci

2022-10-11 18:52 UTC, nemarci commented
Wow, totally forgot about this, thanks for picking it up :)

Looks like you have some minor formatting issue, otherwise it looks good. The issue is that the lines are sometimes too long; maybe the formatting options were changed since I wrote the code, or you maybe copied it into a block with higher indentation level? I'm not sure about the reason, but a `cargo fmt` should solve it.

2023-03-21 16:18 UTC, demoray commented
@jasonk000 I've updated the CHANGELOG.md entry in the PR to move the entry I added to the current "Unreleased" section.

That has triggered a rebuild.  I'll look to address any issues the linter passes identify, but it would be useful to get this integrated.  Is there a person I should be interacting with to help move this PR forward?

2023-03-21 17:40 UTC, bmc-msft commented
@asomers is this a PR you can review for merging?  If not you, can you point me in the right direction?

2023-05-13 05:38 UTC, jasonk000 commented
Bumping with @nemarci hoping we can tag a reviewer. TIA!

2023-07-06 21:23 UTC, bmc-msft commented
cc: @asomers again.   Can this PR get reviewed?  The previous PR, which this was based on was reviewed, but not merged in June of 2021.  This would be helpful for multiple projects to get merged.

2023-07-17 22:24 UTC, asomers requested changes

2023-07-17 22:24 UTC, asomers commented on test/sys/test_ptrace.rs
> +                    // FIXME It's been observed on some systems (apple) the
This comment isn't relevant, as the test is Linux-only.

2023-07-17 22:24 UTC, asomers commented on test/sys/test_ptrace.rs
> +            regs.rax = 0x42424242;
AFAIK, this register name is the only difference between the x86 and x86_64 tests.  Could you combine them to reduce code duplication?  Even better if you can combine them with the setfpregs test too.

2025-07-01 02:01 UTC, drmorr0 commented
@bmc-msft @asomers any updates on this?  would love to get it merged in; I can take a stab at resolving the outstanding issues if needed, but don't want to step on anyone's toes

2025-07-01 15:53 UTC, demoray commented
@drmorr0:  Feel free to take on the outstanding issues.  @bmc-msft is me, though I do not actively use the account anymore.   I'm not using code that would use this feature.

2026-06-05 16:24 UTC, closed without merging