fix: clippy::size_of_ref
nix-rust/nix pull request #1956
Opened 2022-12-31 23:17 UTC by JonathanWoollett-Light

Closes #1955

2023-01-01 00:00 UTC, rtzoeller commented
This change looks correct insofar as it bypasses the clippy warning by being clearer about the intent of the existing code, but I'm not 100% positive the existing code is correct. I'm not very familiar with this part of the nix API though, so I may be mistaken. 

In particular it's not clear to me why we're taking the size of a reference/pointer here, but `af_alg_iv` is larger. Maybe `af_alg_iv.ivlen` is excluded in the length despite being copied?
 
@asomers any ideas?

https://github.com/nix-rust/nix/blob/ed0e859e41fb3611578f759ad2e32a9e98c5dfc0/src/sys/socket/mod.rs#L1210-L1233

2023-01-01 00:07 UTC, JonathanWoollett-Light commented
> I'm not 100% positive the existing code is correct. I'm not very familiar with this part of the nix API though, so I may be mistaken.

It also looks a bit off to me, but for now this change should unblock the CI for other PRs. Fixing any issues in the original behaviour can then be a future PR.

2023-01-02 00:08 UTC, asomers requested changes
It sure seems like the existing code is wrong to me.  I think this would be correct instead.

2023-01-02 00:08 UTC, asomers commented on src/sys/socket/mod.rs
> +                mem::size_of::<&[u8]>() + iv.len()
```suggestion
                mem::size_of_val(iv) + iv.len()
```

2023-01-08 17:56 UTC, rtzoeller approved these changes
I'm submitting this to unblock other PRs; I've filed #1960 to track the suspected underlying issue.

bors r+

2023-01-08 18:06 UTC, merged