Fix endian swap on SocketAddrV6.
nix-rust/nix pull request #1964
Opened 2023-01-10 03:02 UTC by aarond10

This is a bug. flowinfo and scope_id should not be byte swapped here.

See also https://github.com/nix-rust/nix/issues/1963.

2023-01-11 23:02 UTC, asomers requested changes
Sorry for the breakage.  Would it be possible to add a test that demonstrates the problem?  Also, you should add a CHANGELOG entry.
It looks like the bug was introduced by #1711 .

2023-01-12 00:42 UTC, aarond10 commented on Cargo.toml
> -version     = "0.26.1"
Done.

2023-01-12 22:06 UTC, aarond10 commented
This is ready to go now.

2023-01-12 23:26 UTC, asomers requested changes
Looks good, but don't forget the CHANGELOG.

2023-01-13 03:05 UTC, asomers approved these changes
bors r+

2023-01-13 03:17 UTC, merged