Added LOCAL_PEERPID/LocalPeerPid sockopt for macos
nix-rust/nix pull request #1967
Opened 2023-01-11 12:14 UTC by mitsuhiko

macOS has a badly documented `LOCAL_PEERPID` sockopt that can be used to retrieve the PID of the connected peer.

2023-01-14 18:39 UTC, asomers requested changes
Would it be possible to add a test?  It also needs a changelog entry.

2023-01-14 18:51 UTC, mitsuhiko commented
@asomers absolutely. I added a test and changelog entry.

2023-01-15 15:33 UTC, asomers reviewed
Should this be enabled for iOS too?

2023-01-15 21:52 UTC, mitsuhiko commented
I added ios to the conditional compilation and seems like the tests pass.

2023-02-09 01:45 UTC, asomers approved these changes
bors r+

2023-02-09 02:05 UTC, merged