Make `clone` unsafe
nix-rust/nix pull request #1993
Opened 2023-01-31 16:02 UTC by djkoloski

There are many features of `clone` that may cause memory unsafety when called. This documents one of them and references `fork()`, which is already unsafe to call.

Fixes #1975

2023-02-09 01:43 UTC, asomers requested changes
Um yes, clone is nearly impossible to use safely.  I see that the clone binding has been present in Nix since its very first commit in 2014, back before Rust 1.0.  I'm guessing that almost no one has used it since then, which is why nobody has made it `unsafe` yet.  There's only one problem with this PR: could you add a CHANGELOG entry?

2023-02-14 19:54 UTC, djkoloski commented
Sorry for the delay, should be good to go now.

2023-08-27 21:10 UTC, asomers commented
Sorry I missed this PR when last you updated it.  I've just hijacked it to fix the merge conflict.

2023-08-27 21:34 UTC, asomers approved these changes

2023-08-27 21:50 UTC, merged