Add `MSG_WAITFORONE` flag
nix-rust/nix pull request #2014
Opened 2023-03-15 03:32 UTC by stevenengler

I'm not sure what platforms this is defined on, so I listed the ones that I think it's defined on. Below I've listed why I think it's defined on each platform.

- android - android src: https://android.googlesource.com/platform/bionic/+/c7ca8f3/libc/include/sys/socket.h#233
- freebsd - man page: https://man.freebsd.org/cgi/man.cgi?query=recvmmsg&apropos=0&sektion=2&manpath=FreeBSD+11-current&format=html
- fuchsia - defined in rust libc: https://github.com/rust-lang/libc/blob/60bf6d7fa9d561820ea562751ee455ccf67d3015/src/fuchsia/mod.rs#L1768
- illumos - I think this is the illumos src?: https://github.com/TritonDataCenter/illumos-joyent/blob/master/usr/src/uts/common/brand/lx/syscall/lx_socket.c
- linux - man page: https://man7.org/linux/man-pages/man2/recvmmsg.2.html
- netbsd - man page: https://man.netbsd.org/recvfrom.2
- openbsd - man page: https://man.openbsd.org/recvmsg.2
- solaris - man page: https://docs.oracle.com/cd/E88353_01/html/E37843/recvmmsg-3c.html

2023-04-02 13:33 UTC, asomers requested changes
If some definitions are missing from libc, then you should add them there rather than leave them out here.  That's a very common thing to do when adding new functionality to Nix.

2023-05-08 15:22 UTC, stevenengler commented
> If some definitions are missing from libc, then you should add them there rather than leave them out here. That's a very common thing to do when adding new functionality to Nix.

I've added it for more platforms in [libc](https://github.com/rust-lang/libc/pull/3224), and that change is in the latest [libc release](https://github.com/rust-lang/libc/releases/tag/0.2.143).

2023-05-20 15:17 UTC, asomers commented
This PR is still failing because MSG_WAITFORONE isn't defined everywhere.  You need to update the libc spec in Cargo.toml.  Also, I think you need to rebase to fix the failure in Linux armv7 uclibceabihf

2023-08-21 19:15 UTC, stevenengler commented
This is rebased and all tests now pass.

2023-08-26 15:13 UTC, asomers approved these changes

2023-08-26 19:00 UTC, merged