add vsock support for macOS
nix-rust/nix pull request #2056
Opened 2023-06-16 18:27 UTC by tzneal

Adds vsock support for macOS.  It's not possible to create a listening
vsock socket on a macOS host, but you can create one from inside a 
VM and connect back to the host.

2023-07-17 21:36 UTC, asomers requested changes
This needs a CHANGELOG.  Also, I think there will be a merge conflict in Cargo.toml if you don't rebase.

2023-07-18 12:32 UTC, tzneal commented
> This needs a CHANGELOG. Also, I think there will be a merge conflict in Cargo.toml if you don't rebase.

Sounds good, thanks!

2023-08-06 21:27 UTC, asomers approved these changes

2023-08-06 21:28 UTC, asomers commented
There was another CHANGELOG merge conflict, but I fixed that one.

bors r+

2023-08-06 21:40 UTC, merged

2023-08-07 13:33 UTC, tzneal commented
Thanks for fixing the changelog conflict!