Relax lifetime requirements for FdSet::{insert, remove, contains}
nix-rust/nix pull request #2136
Opened 2023-09-23 16:40 UTC by asomers

Fixes #2130

2023-09-23 16:40 UTC, asomers commented
cc @SteveLauC

2023-09-30 07:18 UTC, SteveLauC commented
Seems that these functions should also take a `BorrowedFd`, just like #2134

2023-10-01 01:12 UTC, SteveLauC requested changes

2023-10-01 01:12 UTC, SteveLauC commented on src/sys/select.rs
> +    /// # use std::os::unix::io::{AsFd, AsRawFd, BorrowedFd};
This `AsFd` seems to be unused?

2023-10-01 10:51 UTC, SteveLauC approved these changes

2023-10-01 11:09 UTC, merged