chore: move cargo fmt to pre-commit script
nix-rust/nix pull request #2163
Opened 2023-10-07 06:37 UTC by SteveLauC

## What does this PR do
1. Move `cargo fmt` task to a pre-commit script, and add a doc for it in `CONTRIBUTING.md`
2. Add a doc on how to skip the CI (Cirrus CI, will add the GitHub Action version when we finish our migration) in `CONTRIBUTING.md`

## Checklist:

- [x] I have read `CONTRIBUTING.md`
- [ ] I have written necessary tests and rustdoc comments
- [ ] A change log has been added if this PR modifies nix's API

[skip ci]

2023-10-07 06:44 UTC, SteveLauC commented
Kinda weird, the Cirrus CI still runs even though I explicitly `[skip ci]`

2023-10-07 12:48 UTC, Jan561 commented
It seems you have to include `[skip ci]` in the title of the PR.

```
If you open a PR, PR title will be checked for [skip ci] or [ci skip]
instead of the last commit message on the PR branch.
```

https://cirrus-ci.org/guide/writing-tasks/#conditional-task-execution

2023-10-07 14:09 UTC, asomers commented
I don't know about you, but personally I would find it surprising if the pre-commit script actually changed my code, as opposed to merely checking it.  Also, I don't think that the addition of a pre-commit script absolves us from running rustfmt in CI.  Because what if some contributor doesn't run the pre-commit script?  We have no way to force them to.

2023-10-07 14:35 UTC, SteveLauC commented
> Also, I don't think that the addition of a pre-commit script absolves us from running rustfmt in CI. Because what if some contributor doesn't run the pre-commit script? We have no way to force them to.

Then it seems that we have to add rustfmt to our CI, because AFAIK, there is no way to make this check compulsory with a pre-commit script

2023-10-08 00:15 UTC, SteveLauC commented
> It seems you have to include `[skip ci]` in the title of the PR.
> 
> ```
> If you open a PR, PR title will be checked for [skip ci] or [ci skip]
> instead of the last commit message on the PR branch.
> ```
> 
> https://cirrus-ci.org/guide/writing-tasks/#conditional-task-execution
> 
> Still weird though as it worked in #2158.

Yeah, it is indeed weird :<

2023-10-13 15:54 UTC, asomers requested changes

2023-10-13 15:54 UTC, asomers commented on pre-commit.sh
> +function red() {
The `function` is bash syntax, not sh.
```suggestion
red() {
```

2023-10-13 15:54 UTC, asomers commented on pre-commit.sh
> +cargo fmt --all -q -- --check 2>/dev/null
This command doesn't actually work.  I just tested it by screwing up the format in src/sys/aio.rs, and this command didn't complain.  I think it's caused by this bug: https://github.com/rust-lang/rustfmt/issues/3253 .  That's why we need to do `cargo fmt --all -- --check **/*.rs`

2023-10-13 16:03 UTC, SteveLauC commented
For the format check, are we gonna use a pre-commit script or do it in CI? 

#2166 has migrated it to GHA, so if we choose the latter, then we can simply close this PR

2023-11-04 15:51 UTC, asomers commented
Yeah, I think we can close this PR if we merge the other one too.  The pre-commit.sh script _could_ be useful too, but maybe not useful enough to justify its ongoing maintenance.

2023-11-05 02:06 UTC, SteveLauC commented
Close this PR

2023-11-05 02:06 UTC, closed without merging