Add more cfg aliases
nix-rust/nix pull request #2205
Opened 2023-11-24 00:34 UTC by asomers

Add cfg aliases for linux_android, bsd, and freebsdlike.  Use them in many places, though not everywhere they could theoretically be used.

Fixes #2188

## What does this PR do

## Checklist:

- [x] I have read `CONTRIBUTING.md`
- [ ] I have written necessary tests and rustdoc comments
- [ ] A change log has been added if this PR modifies nix's API

2023-11-24 01:01 UTC, SteveLauC commented
Should we also do this for Solaris and Illumos?

```rs
cfg_aliases! {
    illumos: { target_os = "illumos" },
    solaris: { target_os = "solaris" },
        
    solarish: { any(solaris, illumos) }
}
```


BTW, we should document this in probably `CONVENTIONS.md` (or `CONTRIBUTING.md`?) so that our contributors can be aware of these aliases and use them in PRs

2023-11-24 02:14 UTC, SteveLauC commented on build.rs
> +        bsd: { any(freebsd, dragonfly, ios, macos, netbsd, openbsd, tvos, watchos) },
Might be better to use the defined `apple_targets` here:

```suggestion
        bsd: { any(freebsd, dragonfly, netbsd, openbsd, apple_targets) },
```

2023-11-24 02:16 UTC, SteveLauC commented on build.rs
> +        freebsdlike: { any(dragonfly, freebsd)}
```suggestion
        freebsdlike: { any(dragonfly, freebsd) }
```

2023-11-24 17:23 UTC, Jan561 commented
Are other config-aliases, like an alias `mmsg` for
```rust
#[cfg(all(
    feature = "socket",
    feature = "uio",
    any(
        target_os = "linux",
        target_os = "android",
        target_os = "freebsd",
        target_os = "netbsd",
    ),
))]
```
desirable for the future? Or should they just stay platform-related for the time being?

2023-11-24 18:15 UTC, asomers commented
> Are other config-aliases, like an alias `mmsg` for
> 
> ```rust
> #[cfg(all(
>     feature = "socket",
>     feature = "uio",
>     any(
>         target_os = "linux",
>         target_os = "android",
>         target_os = "freebsd",
>         target_os = "netbsd",
>     ),
> ))]
> ```
> 
> desirable for the future? Or should they just stay platform-related for the time being?

I think we can add them on an as-needed basis.

2023-11-25 05:34 UTC, SteveLauC requested changes

2023-11-25 05:49 UTC, SteveLauC commented
I just checked that the changes made in this PR are good.

But there are also still `cfg`s that haven't been updated, we should handle them as well, but not in this PR, instead, we should probably split the remaining job into several PRs, which will make code review easier.

For #2188, let's turn it into a tracking issue, once the tasks in it are all done, then we can close it.

----------

For the requested changes, I have committed 2 with the GitHub UI, please ignore the left ones and handle them in other PRs

2023-11-25 06:49 UTC, merged