impl Display for InterfaceFlags
nix-rust/nix pull request #2206
Opened 2023-11-24 18:15 UTC by asomers

And add a full example for getifaddrs.

## What does this PR do

implements fmt::Display for InterfaceFlags, and adds an example for getifaddrs

## Checklist:

- [x] I have read `CONTRIBUTING.md`
- [x] I have written necessary tests and rustdoc comments
- [x] A change log has been added if this PR modifies nix's API

2023-11-25 08:28 UTC, SteveLauC requested changes
Changes LGTM, but since #2205 has been merged, we should use aliases here

2023-11-25 08:28 UTC, SteveLauC commented on examples/getifaddrs.rs
> +))]
```suggestion
#[cfg(any(bsd, linux_android, target_os = "illumos"))]
```

2023-11-25 08:28 UTC, SteveLauC commented on examples/getifaddrs.rs
> +)))]
```suggestion
#[cfg(not(any(bsd, linux_android, target_os = "illumos")))]
```

2023-11-25 16:37 UTC, asomers commented
Rebased and applied cfg aliases.

2023-11-26 00:09 UTC, SteveLauC approved these changes

2023-11-26 00:28 UTC, merged