refactor: enable most macOS funcs for apple_targets
nix-rust/nix pull request #2241
Opened 2023-12-01 12:32 UTC by SteveLauC

## What does this PR do

1. Enable most macOS functions for apple_targets
2. Disable `ClockId::setime()` on Apple targets other than macOS

Closes #2238

## Checklist:

- [x] I have read `CONTRIBUTING.md`
- [ ] I have written necessary tests and rustdoc comments
- [x] A change log has been added if this PR modifies nix's API

2023-12-01 12:33 UTC, SteveLauC commented on src/time.rs
> +    #[cfg(not(any(
Enable it only on macOS

2023-12-01 14:44 UTC, asomers requested changes

2023-12-01 14:44 UTC, asomers commented on changelog/2241.changed.md
> +`ClockId::set_time()` has been disabled on iOS/tvOS/watchOS given that it is only available on macOS
It was already disabled on iOS/tvOS/watchOS.  Shouldn't this read "ClockId::set_time is now enabled on macos" ?

2023-12-01 14:44 UTC, asomers commented on src/time.rs
> +        target_os = "macos",
Did you not notice the `not` ?
```suggestion
    #[cfg(not(any(
        target_os = "ios",
        target_os = "tvos",
        target_os = "watchos",
```

2023-12-02 08:08 UTC, SteveLauC commented on src/time.rs
> +        target_os = "macos",
Oops, I am sorry I missed that, fixed!

2023-12-02 16:57 UTC, asomers approved these changes

2023-12-02 17:27 UTC, merged