fcntl adding apple F_PREALLOCATE flag.
nix-rust/nix pull request #2393
Opened 2024-05-05 08:45 UTC by devnexen

## What does this PR do

## Checklist:

- [x] I have read `CONTRIBUTING.md`
- [x] I have written necessary tests and rustdoc comments
- [ ] A change log has been added if this PR modifies nix's API

2024-05-05 11:51 UTC, SteveLauC commented
I am working on the CI issues, they are not related to this PR

2024-05-17 09:36 UTC, SteveLauC commented
Gentle ping on this PR, would you like to rebase and finish it?

2024-05-17 10:15 UTC, devnexen commented
seems libc 0.2.154 not yet available (just the tag on the repo but not yet published maybe) ?

2024-05-17 10:17 UTC, SteveLauC commented
> seems libc 0.2.154 not yet available (just the tag on the repo but not yet published maybe) ?

Right, it has been yanked, we have to wait for https://github.com/rust-lang/libc/pull/3682

2024-05-18 09:06 UTC, SteveLauC commented
The issue has been fixed, please rebase your branch:)

2024-05-19 02:55 UTC, SteveLauC requested changes

2024-05-19 02:55 UTC, SteveLauC commented on src/fcntl.rs
> +    F_PREALLOCATE(&'a libc::fstore_t),
The associated buffer has an `OUT` field: 

```c
typedef struct fstore {
	    u_int32_t fst_flags;      /* IN: flags word */
	    int       fst_posmode;    /* IN: indicates offset field */
	    off_t     fst_offset;     /* IN: start of the region */
	    off_t     fst_length;     /* IN: size of the region */
	    off_t     fst_bytesalloc; /* OUT: number of bytes allocated */
} fstore_t;
```

i.e., the buffer can be written, if we use an immutable reference here, then UB could happen


Ref: https://keith.github.io/xcode-man-pages/fcntl.2.html#F_PREALLOCATE

2024-05-19 02:55 UTC, SteveLauC commented on src/fcntl.rs
> +    F_PREALLOCATE(&'a libc::fstore_t),
I just tried implementing this on my mac, I think we should create a helper type for those `IN` fields, and return the `OUT` field through `fcntl()`.

For that `fst_falgs` field, we would create a bitflags struct, for `fst_posmode`, a Rust enum would suffice.


And [F_ALLOCATEPERSIST](https://keith.github.io/xcode-man-pages/fcntl.2.html#F_ALLOCATEPERSIST) is not available in libc, we should add it first.

2024-05-19 03:06 UTC, SteveLauC commented on src/fcntl.rs
> +    F_PREALLOCATE(&'a libc::fstore_t),
libc PR filed: https://github.com/rust-lang/libc/pull/3713

2024-09-06 02:59 UTC, SteveLauC commented on src/fcntl.rs
> +    /// Pre-allocate storage with different policies on fd.
Do you think we shoud document the reason why a mutable reference is needed here? i.e., there is a OUT field in the associated sturcutre🤔

2024-09-06 05:53 UTC, SteveLauC approved these changes
LGTM, thanks!

2024-09-06 05:54 UTC, SteveLauC commented
Looks like you need to resolve the conflict in `src/fcntl.rs`.

2024-09-06 07:12 UTC, merged